// The files an ATC installation consists of.
//
// Generated rather than copied. Three of them have to be, because they depend
// on settings this panel owns:
//
//   - `atcTestToolPresent.g` reads `sensors.gpIn[N]`, where N is the same
//     number as the `M950 J<N>` in atcConfig.g. Ship it as a fixed file and it
//     silently watches the wrong input — which reads as "the sensor never sees
//     a tool" and stops every pickup with a prompt.
//   - `tpost<n>.g` / `tfree<n>.g` are one pair per pocket, identical apart from
//     the slot number, and there have to be exactly as many as there are
//     pockets.
//   - `atcConfig.g` is the settings themselves.
//
// The rest could have been static assets, but generating them keeps the whole
// installation in one place and lets the dust-shoe hooks and the tool sensor
// drop out entirely on a machine that has neither, instead of shipping macros
// full of `if exists(...)` for hardware nobody has.
//
// Adapted from the macros published for the RapidChange ATC, which is the
// mechanism these drive. The sequences — descend at low RPM, lift to re-seat
// the threads, verify — are the manufacturer's; the RepRapFirmware phrasing and
// the generation are this project's.

import { renderAtcConfig, type AtcConfig } from './config.js';

export interface AtcFile {
  /** Name within the controller's config directory. */
  name: string;
  content: string;
  /** What it is for, shown in the install preview. */
  purpose: string;
}

const HEADER = '; Generated by Axis Control. Changes here are lost on reinstall.';

/**
 * Every file an installation writes, given a configuration.
 *
 * Pure: it touches nothing and reads nothing, so the panel can render exactly
 * this list — names, sizes and contents — before anything is sent.
 */
export function atcFiles(config: AtcConfig): AtcFile[] {
  const files: AtcFile[] = [
    {
      name: 'atcConfig.g',
      content: renderAtcConfig(config),
      purpose: 'Settings and pin definitions. Call it from config.g.',
    },
    {
      name: 'atcPickup.g',
      content: pickup(config),
      purpose: 'Screw a tool on from a pocket.',
    },
    {
      name: 'atcDrop.g',
      content: drop(config),
      purpose: 'Unscrew the current tool into a pocket.',
    },
  ];

  if (config.probingEnabled) {
    files.push({
      name: 'atcProbeZ.g',
      content: probeZ(config),
      purpose: 'Measure tool length and set the tool offset.',
    });
  }

  if (config.hasToolSensor) {
    files.push({
      name: 'atcTestToolPresent.g',
      content: testToolPresent(config),
      purpose: `Read the tool sensor on gpIn[${config.toolSensorIn}], debounced.`,
    });
  }

  if (config.hasDustCover) {
    files.push(
      {
        name: 'atcOpenDustCover.g',
        content: `${HEADER}\nM42 P${config.dustCoverOut} S1\nG4 S1\n`,
        purpose: 'Open the pocket cover and wait for it.',
      },
      {
        name: 'atcCloseDustCover.g',
        content: `${HEADER}\nM42 P${config.dustCoverOut} S0\nG4 S1\n`,
        purpose: 'Close it again.',
      },
    );
  }

  // Tool 0 is "no tool" in RRF, so its three files exist and do nothing —
  // without them a T0 falls through to whatever was there before.
  files.push(
    { name: 'tfree0.g', content: `${HEADER}\n; T0 is "no tool" — nothing to drop.\n`, purpose: 'T0: no-op.' },
    { name: 'tpre0.g', content: `${HEADER}\n; T0 is "no tool" — nothing to fetch.\n`, purpose: 'T0: no-op.' },
    { name: 'tpost0.g', content: `${HEADER}\n; T0 is "no tool" — nothing to probe.\n`, purpose: 'T0: no-op.' },
  );

  for (let slot = 1; slot <= config.count; slot++) {
    files.push(
      { name: `tfree${slot}.g`, content: tfree(config, slot), purpose: `Drop tool ${slot}.` },
      { name: `tpre${slot}.g`, content: tpre(slot), purpose: `Before tool ${slot}.` },
      { name: `tpost${slot}.g`, content: tpost(config, slot), purpose: `Fetch and probe tool ${slot}.` },
    );
  }

  return files;
}

// --- Tool change hooks ------------------------------------------------------
//
// RRF calls tfree on the outgoing tool, then tpre, then tpost on the incoming
// one. The pickup belongs in tpost rather than tpre because tpre runs before
// the tool number has actually changed, and the probe that follows sets the
// offset for the tool being selected.

function shoeRetract(config: AtcConfig): string {
  return config.dustShoe
    ? 'if {exists(global.dustShoeEngaged)}\n\tM98 P"dustShoeRetract.g"\n'
    : '';
}

function shoeEngage(config: AtcConfig): string {
  return config.dustShoe
    ? 'if {exists(global.dustShoeEngaged)}\n\tM98 P"dustShoeEngage.g"\n'
    : '';
}

function tfree(config: AtcConfig, slot: number): string {
  return `${HEADER}\n; Called when tool ${slot} is freed.\n\n${shoeRetract(config)}M98 P"atcDrop.g" S${slot}\n`;
}

function tpre(slot: number): string {
  return `${HEADER}\n; Called before tool ${slot} is selected. The pickup is in tpost,\n; which runs once the tool number has actually changed.\n`;
}

function tpost(config: AtcConfig, slot: number): string {
  const probe = config.probingEnabled ? `M98 P"atcProbeZ.g" S${slot}\n` : '';
  return `${HEADER}\n; Called after tool ${slot} has been selected.\n\n${shoeRetract(config)}M98 P"atcPickup.g" S${slot}\n${probe}${shoeEngage(config)}`;
}

// --- Operations -------------------------------------------------------------

/** Guard clauses every operation shares. */
function preamble(what: string): string {
  return `${HEADER}
; ${what}

; The S check comes first: echoing param.S before knowing it exists is itself
; an error, and an error inside a tool-change macro aborts the job.
if {!exists(param.S)}
\techo "atc: this macro expects an S parameter (the slot number)"
\tM99

echo "ATC ${what} #" ^ {param.S}

if {global.atcEnabled = false}
\techo "ATC disabled — skipping"
\tM99

if {param.S < 1 || param.S > global.atcCount}
\techo "atc: slot " ^ {param.S} ^ " is outside the 1.." ^ {global.atcCount} ^ " configured"
\tM99

G90 ; absolute
G94 ; feed per minute
G17 ; XY plane
G21 ; millimetres
`;
}

const SLOT_MOVE =
  'G53 G0 X{global.atcOriginX + global.atcOffsetX * (param.S - 1)} Y{global.atcOriginY + global.atcOffsetY * (param.S - 1)}';

function openCover(config: AtcConfig): string {
  return config.hasDustCover ? 'M98 P"atcOpenDustCover.g"\n' : '';
}
function closeCover(config: AtcConfig): string {
  return config.hasDustCover ? 'M98 P"atcCloseDustCover.g"\n' : '';
}

function pickup(config: AtcConfig): string {
  // The lift-and-re-descend is not redundant: the first descent starts the
  // thread, the lift lets it settle, and the second seats it. Skipping it
  // cross-threads the nut often enough to matter.
  const verify = config.hasToolSensor
    ? `
; Verify the tool actually came out of the pocket.
G53 G0 Z{global.atcPickupStartZ + 5}
G4 S1
M98 P"atcTestToolPresent.g"
while {!global.atcToolHasBeenDetected}
\tG53 G0 Z{global.atcRetractZ}
\tM291 R"Tool pickup failed" P"No tool was detected. Fit it by hand, then continue." S2
\tG53 G0 Z{global.atcPickupStartZ + 5}
\tM98 P"atcTestToolPresent.g"
`
    : '';

  return `${preamble('pickup tool')}
${openCover(config)}G53 G0 Z{global.atcRetractZ}
${SLOT_MOVE}
G53 G0 Z{global.atcPickupStartZ}

M400
M3 S{global.atcPickupRPM} ; clockwise, to screw on
G4 S{global.atcSpindlePause}

G53 G1 Z{global.atcPickupEndZ} F{global.atcPickupFeed}
G53 G1 Z{global.atcPickupEndZ + global.atcPickupReengage}
G4 S0.25
G53 G1 Z{global.atcPickupEndZ} F{global.atcPickupFeed}
G53 G0 Z{global.atcPickupStartZ}

M400
M5
${verify}
G53 G0 Z{global.atcRetractZ}
${closeCover(config)}`;
}

function drop(config: AtcConfig): string {
  const verify = config.hasToolSensor
    ? `
; Verify the tool actually went into the pocket.
G53 G0 Z{global.atcPickupStartZ + 5}
G4 S1
M98 P"atcTestToolPresent.g"
if {global.atcToolHasBeenDetected}
\tG53 G0 Z{global.atcRetractZ}
\tM291 R"Tool drop failed" P"A tool is still detected. Remove it by hand, then continue." S2
`
    : '';

  return `${preamble('drop tool')}
${openCover(config)}G53 G0 Z{global.atcRetractZ}
${SLOT_MOVE}
G53 G0 Z{global.atcDropStartZ}

M400
M4 S{global.atcDropRPM} ; anticlockwise, to unscrew
G4 S{global.atcSpindlePause}

G53 G1 Z{global.atcDropEndZ} F{global.atcDropFeed}
G53 G1 Z{global.atcDropStartZ}

M400
M5
${verify}
G53 G0 Z{global.atcRetractZ}
${closeCover(config)}`;
}

function probeZ(config: AtcConfig): string {
  // G10 L1 is zeroed first so the probe measures the tool rather than the tool
  // plus whatever offset was left over from the last one.
  const shoe = config.dustShoe
    ? ' U{-var.newOffset} ; and the dust shoe follows the tool'
    : '';
  return `${HEADER}
; Measure the tool in the spindle against the fixed probe.

if {global.atcEnabled = false}
\techo "ATC disabled — skipping probe"
\tM99

if {global.atcProbingEnabled = false}
\techo "ATC probing disabled — skipping"
\tM99

G21
G90
G53 G0 Z{global.atcRetractZ}
G53 G0 X{global.atcProbeX} Y{global.atcProbeY}

G10 L1 X0 Y0 Z0 ; clear the current tool offset before measuring
echo "Probing Z from " ^ {move.axes[2].machinePosition}
M585 Z{-(global.atcRetractZ - global.atcProbeZ)} P{global.atcProbeIndex} F500 S1
var newOffset = {-(move.axes[2].machinePosition - global.atcProbeZ)}
echo "Tool offset " ^ {var.newOffset} ^ " (probe at Z " ^ {global.atcProbeZ} ^ ")"
G10 L1 Z{var.newOffset}${shoe}

G53 G0 Z{global.atcRetractZ}
`;
}

function testToolPresent(config: AtcConfig): string {
  // Ten reads over a second, not one: the beam is noisy while the spindle
  // spins down, and a single sample decides "no tool" often enough to be
  // useless. Two hits out of ten is the threshold the sequences were tuned on.
  return `${HEADER}
; Is a tool in the spindle? Result in global.atcToolHasBeenDetected.
; Reads gpIn[${config.toolSensorIn}], which is the M950 J${config.toolSensorIn} in atcConfig.g.

if !{exists(global.atcToolHasBeenDetected)}
\tglobal atcToolHasBeenDetected = true

set global.atcToolHasBeenDetected = true
var loopCounter = 0
var counter = 0

while var.loopCounter < 10
\tG4 P100
\tset var.loopCounter = iterations
\tset var.counter = {var.counter + sensors.gpIn[${config.toolSensorIn}].value}
\tset global.atcToolHasBeenDetected = var.counter < 2

if global.atcToolHasBeenDetected
\techo "Tool detected"
else
\techo "No tool detected"
`;
}
