// The files an ATC installation consists of.
//
// Generated rather than copied, because they depend on settings this panel
// owns:
//
//   - `atcConfig.g` is the settings themselves.
//   - `atcBank.g` selects one bank of pockets. It is generated because it is
//     literally a table of the banks that exist.
//   - `atcTestToolPresent.g` reads `sensors.gpIn[N]`, where N is the same
//     number as the `M950 J<N>` in atcConfig.g. Ship it as a fixed file and it
//     silently watches the wrong input — which reads as "the sensor never sees
//     a tool" and stops every pickup with a prompt.
//   - `tpost<n>.g` / `tfree<n>.g` are one pair per tool, and each has to know
//     which bank and which pocket that tool lives in.
//
// The rest could have been static assets, but generating them keeps the whole
// installation in one place and lets the dust-shoe hooks and the tool sensor
// drop out entirely on a machine that has neither, instead of shipping macros
// full of `if exists(...)` for hardware nobody has.
//
// The banks are handled by copying one bank's numbers into a set of "current"
// globals rather than by passing a dozen parameters around. It costs one macro
// call at the top of each operation and means every sequence below reads the
// same names it always did — which is also what makes a bank cheap to add.
//
// Adapted from the macros published for the RapidChange ATC, which is the
// mechanism these drive. The sequences — descend at low RPM, lift to re-seat
// the threads, verify — are the manufacturer's; the RepRapFirmware phrasing and
// the generation are this project's.

import { bankFields, renderAtcConfig, toolNumber, type AtcConfig } from './config.js';

export interface AtcFile {
  /** Name within the controller's config directory. */
  name: string;
  content: string;
  /** What it is for, shown in the install preview. */
  purpose: string;
}

const HEADER = '; Generated by Axis Control. Changes here are lost on reinstall.';

export interface AtcFileOptions {
  /**
   * True when the firmware itself keeps the dust-shoe axis level with the tool
   * (M604), which makes the inverse-offset term in atcProbeZ.g redundant.
   *
   * Passed in rather than worked out here, because working it out means asking
   * the board, and this function is pure so that the panel can show exactly
   * what will be written before anything is sent. Defaulting to false is the
   * safe direction: the term is harmless where it is not needed and load-bearing
   * where it is. See core/dustshoe.ts.
   */
  dustShoeFollowsInFirmware?: boolean;
}

/**
 * Every file an installation writes, given a configuration.
 *
 * Pure: it touches nothing and reads nothing, so the panel can render exactly
 * this list — names, sizes and contents — before anything is sent.
 */
export function atcFiles(config: AtcConfig, opts: AtcFileOptions = {}): AtcFile[] {
  const anyCover = config.banks.some((b) => b.cover);

  const files: AtcFile[] = [
    {
      name: 'atcConfig.g',
      content: renderAtcConfig(config),
      purpose: 'Settings and pin definitions. Call it from config.g.',
    },
    {
      name: 'atcBank.g',
      content: selectBank(config),
      purpose:
        config.banks.length > 1
          ? `Select one of the ${config.banks.length} banks of pockets.`
          : 'Select the bank of pockets.',
    },
    { name: 'atcPickup.g', content: pickup(config), purpose: 'Screw a tool on from a pocket.' },
    { name: 'atcDrop.g', content: drop(config), purpose: 'Unscrew the current tool into a pocket.' },
  ];

  if (config.probingEnabled) {
    files.push({
      name: 'atcProbeZ.g',
      content: probeZ(config, opts.dustShoeFollowsInFirmware === true),
      purpose: 'Measure tool length and set the tool offset.',
    });
  }

  if (config.hasToolSensor) {
    files.push({
      name: 'atcTestToolPresent.g',
      content: testToolPresent(config),
      purpose: `Read the tool sensor on gpIn[${config.toolSensorIn}], debounced.`,
    });
  }

  if (anyCover) {
    files.push(
      {
        name: 'atcOpenDustCover.g',
        content: cover(1),
        purpose: "Open the selected bank's pocket cover and wait for it.",
      },
      { name: 'atcCloseDustCover.g', content: cover(0), purpose: 'Close it again.' },
    );
  }

  // Tool 0 is "no tool" in RRF, so its three files exist and do nothing —
  // without them a T0 falls through to whatever was there before.
  files.push(
    { name: 'tfree0.g', content: `${HEADER}\n; T0 is "no tool" — nothing to drop.\n`, purpose: 'T0: no-op.' },
    { name: 'tpre0.g', content: `${HEADER}\n; T0 is "no tool" — nothing to fetch.\n`, purpose: 'T0: no-op.' },
    { name: 'tpost0.g', content: `${HEADER}\n; T0 is "no tool" — nothing to probe.\n`, purpose: 'T0: no-op.' },
  );

  config.banks.forEach((bank, b) => {
    const where = config.banks.length > 1 ? ` (${bank.name} pocket ` : ' (pocket ';
    for (let slot = 1; slot <= bank.count; slot++) {
      const tool = toolNumber(config, b, slot);
      const at = `${where}${slot})`;
      files.push(
        { name: `tfree${tool}.g`, content: tfree(config, b, slot, tool), purpose: `Drop tool ${tool}${at}.` },
        { name: `tpre${tool}.g`, content: tpre(tool, at), purpose: `Before tool ${tool}.` },
        { name: `tpost${tool}.g`, content: tpost(config, b, slot, tool), purpose: `Fetch and probe tool ${tool}${at}.` },
      );
    }
  });

  return files;
}

// --- Bank selection ---------------------------------------------------------

/**
 * atcBank.g: copy one bank's numbers into the "current bank" globals.
 *
 * An if-chain over literal bank numbers rather than anything cleverer, because
 * a global cannot be looked up by a computed name in RRF and this file is
 * generated anyway. It reads as exactly what it is — the table of banks — which
 * matters when someone is standing at the machine working out why a tool change
 * went to the wrong side of the table.
 */
function selectBank(config: AtcConfig): string {
  const arms = config.banks.map((bank, i) => {
    const keyword = i === 0 ? 'if' : 'elif';
    const sets = bankFields(config, i).map((f) => `\tset global.atcCur${f.name} = global.atcB${i}${f.name}`);
    return `${keyword} {param.B = ${i}}\n\t; ${bank.name}\n${sets.join('\n')}`;
  });

  return `${HEADER}
; Select a bank of pockets:  M98 P"atcBank.g" B{n}
;
; Every operation calls this first, then reads global.atcCur*. Adding a bank in
; the ATC panel rewrites this file; nothing else needs to change.

if {!exists(param.B)}
\techo "atc: atcBank.g expects a B parameter (the bank number)"
\tM99

if {param.B < 0 || param.B >= global.atcBankCount}
\techo "atc: bank " ^ {param.B} ^ " does not exist (0.." ^ {global.atcBankCount - 1} ^ ")"
\tM99

set global.atcCurBank = {param.B}

${arms.join('\n')}
`;
}

// --- Tool change hooks ------------------------------------------------------
//
// RRF calls tfree on the outgoing tool, then tpre, then tpost on the incoming
// one. The pickup belongs in tpost rather than tpre because tpre runs before
// the tool number has actually changed, and the probe that follows sets the
// offset for the tool being selected.

function shoeRetract(config: AtcConfig): string {
  return config.dustShoe ? 'if {exists(global.dustShoeEngaged)}\n\tM98 P"dustShoeRetract.g"\n' : '';
}

function shoeEngage(config: AtcConfig): string {
  return config.dustShoe ? 'if {exists(global.dustShoeEngaged)}\n\tM98 P"dustShoeEngage.g"\n' : '';
}

function tfree(config: AtcConfig, bank: number, slot: number, tool: number): string {
  return `${HEADER}\n; Called when tool ${tool} is freed — ${config.banks[bank].name}, pocket ${slot}.\n\n${shoeRetract(config)}M98 P"atcDrop.g" B${bank} S${slot}\n`;
}

function tpre(tool: number, at: string): string {
  return `${HEADER}\n; Called before tool ${tool}${at} is selected. The pickup is in tpost,\n; which runs once the tool number has actually changed.\n`;
}

function tpost(config: AtcConfig, bank: number, slot: number, tool: number): string {
  const probe = config.probingEnabled ? `M98 P"atcProbeZ.g" B${bank} S${slot}\n` : '';
  return `${HEADER}\n; Called after tool ${tool} has been selected — ${config.banks[bank].name}, pocket ${slot}.\n\n${shoeRetract(config)}M98 P"atcPickup.g" B${bank} S${slot}\n${probe}${shoeEngage(config)}`;
}

// --- Operations -------------------------------------------------------------

/** Guard clauses every operation shares, including selecting the bank. */
function preamble(what: string): string {
  return `${HEADER}
; ${what}

; The parameter checks come first: echoing param.S before knowing it exists is
; itself an error, and an error inside a tool-change macro aborts the job.
if {!exists(param.S) || !exists(param.B)}
\techo "atc: this macro expects B (bank) and S (pocket) parameters"
\tM99

if {global.atcEnabled = false}
\techo "ATC disabled — skipping"
\tM99

M98 P"atcBank.g" B{param.B}
echo "ATC ${what} #" ^ {param.S} ^ " from " ^ {global.atcCurBank}

if {param.S < 1 || param.S > global.atcCurCount}
\techo "atc: pocket " ^ {param.S} ^ " is outside the 1.." ^ {global.atcCurCount} ^ " this bank has"
\tM99

G90 ; absolute
G94 ; feed per minute
G17 ; XY plane
G21 ; millimetres
`;
}

const SLOT_MOVE =
  'G53 G0 X{global.atcCurOriginX + global.atcCurOffsetX * (param.S - 1)} Y{global.atcCurOriginY + global.atcCurOffsetY * (param.S - 1)}';

/** The cover macros, which act only on banks that have one. */
function cover(state: 0 | 1): string {
  return `${HEADER}
; ${state ? 'Open' : 'Close'} the selected bank's pocket cover.
; Banks without one set atcCurCoverOut to -1, and this does nothing.

if {global.atcCurCoverOut >= 0}
\tM42 P{global.atcCurCoverOut} S${state}
\tG4 S1
`;
}

function openCover(config: AtcConfig): string {
  return config.banks.some((b) => b.cover) ? 'M98 P"atcOpenDustCover.g"\n' : '';
}
function closeCover(config: AtcConfig): string {
  return config.banks.some((b) => b.cover) ? 'M98 P"atcCloseDustCover.g"\n' : '';
}

function pickup(config: AtcConfig): string {
  // The lift-and-re-descend is not redundant: the first descent starts the
  // thread, the lift lets it settle, and the second seats it. Skipping it
  // cross-threads the nut often enough to matter.
  const verify = config.hasToolSensor
    ? `
; Verify the tool actually came out of the pocket.
G53 G0 Z{global.atcCurPickupStartZ + 5}
G4 S1
M98 P"atcTestToolPresent.g"
while {!global.atcToolHasBeenDetected}
\tG53 G0 Z{global.atcRetractZ}
\tM291 R"Tool pickup failed" P"No tool was detected. Fit it by hand, then continue." S2
\tG53 G0 Z{global.atcCurPickupStartZ + 5}
\tM98 P"atcTestToolPresent.g"
`
    : '';

  return `${preamble('pickup tool')}
${openCover(config)}G53 G0 Z{global.atcRetractZ}
${SLOT_MOVE}
G53 G0 Z{global.atcCurPickupStartZ}

M400
M3 S{global.atcPickupRPM} ; clockwise, to screw on
G4 S{global.atcSpindlePause}

G53 G1 Z{global.atcCurPickupEndZ} F{global.atcCurPickupFeed}
G53 G1 Z{global.atcCurPickupEndZ + global.atcCurPickupReengage}
G4 S0.25
G53 G1 Z{global.atcCurPickupEndZ} F{global.atcCurPickupFeed}
G53 G0 Z{global.atcCurPickupStartZ}

M400
M5
${verify}
G53 G0 Z{global.atcRetractZ}
${closeCover(config)}`;
}

function drop(config: AtcConfig): string {
  const verify = config.hasToolSensor
    ? `
; Verify the tool actually went into the pocket.
G53 G0 Z{global.atcCurPickupStartZ + 5}
G4 S1
M98 P"atcTestToolPresent.g"
if {global.atcToolHasBeenDetected}
\tG53 G0 Z{global.atcRetractZ}
\tM291 R"Tool drop failed" P"A tool is still detected. Remove it by hand, then continue." S2
`
    : '';

  return `${preamble('drop tool')}
${openCover(config)}G53 G0 Z{global.atcRetractZ}
${SLOT_MOVE}
G53 G0 Z{global.atcCurDropStartZ}

M400
M4 S{global.atcDropRPM} ; anticlockwise, to unscrew
G4 S{global.atcSpindlePause}

G53 G1 Z{global.atcCurDropEndZ} F{global.atcCurDropFeed}
G53 G1 Z{global.atcCurDropStartZ}

M400
M5
${verify}
G53 G0 Z{global.atcRetractZ}
${closeCover(config)}`;
}

function probeZ(config: AtcConfig, shoeFollowsInFirmware: boolean): string {
  // G10 L1 is zeroed first so the probe measures the tool rather than the tool
  // plus whatever offset was left over from the last one.
  //
  // The U term does not move the shoe. It shifts the shoe axis's WORK
  // coordinate by the inverse of the tool offset, so that dustShoeEngage.g's
  // fixed work-coordinate target lands at a machine position corrected for tool
  // length. Under M604 the firmware holds the two axes together in machine
  // coordinates after tool offsets and does that correction itself, so the term
  // becomes redundant — harmless, since a derived coordinate ignores its own
  // tool offset and cannot compensate twice, but misleading to leave in.
  const shoe =
    config.dustShoe && !shoeFollowsInFirmware
      ? ' U{-var.newOffset} ; and the dust shoe follows the tool'
      : '';
  const perBank = config.banks.some((b) => b.probe);
  // Said in the file itself, because the absence of a U term is not evidence of
  // anything to whoever opens this on the card a year from now — it looks
  // exactly like a machine with no dust shoe.
  const shoeNote =
    config.dustShoe && shoeFollowsInFirmware
      ? ';\n; The dust shoe is not touched here: the firmware holds its axis to Z\n; itself (M604), in machine coordinates and after tool offsets, so tool\n; length is already accounted for.\n'
      : '';
  return `${HEADER}
; Measure the tool in the spindle against the tool setter.
;
; The setter is whichever one belongs to the bank the tool came from:
; atcBank.g has already put its position into global.atcCurProbe*, which is
; the machine-wide setter unless${perBank ? ' that bank has its own.' : ' a bank is given its own.'}
${shoeNote}
if {global.atcEnabled = false}
\techo "ATC disabled — skipping probe"
\tM99

if {global.atcProbingEnabled = false}
\techo "ATC probing disabled — skipping"
\tM99

if {exists(param.B)}
\tM98 P"atcBank.g" B{param.B}

G21
G90
G53 G0 Z{global.atcRetractZ}
G53 G0 X{global.atcCurProbeX} Y{global.atcCurProbeY}

G10 L1 X0 Y0 Z0 ; clear the current tool offset before measuring
echo "Probing Z from " ^ {move.axes[2].machinePosition}
M585 Z{-(global.atcRetractZ - global.atcCurProbeZ)} P{global.atcCurProbeIndex} F500 S1
var newOffset = {-(move.axes[2].machinePosition - global.atcCurProbeZ)}
echo "Tool offset " ^ {var.newOffset} ^ " (setter at Z " ^ {global.atcCurProbeZ} ^ ")"
G10 L1 Z{var.newOffset}${shoe}

G53 G0 Z{global.atcRetractZ}
`;
}

function testToolPresent(config: AtcConfig): string {
  // Ten reads over a second, not one: the beam is noisy while the spindle
  // spins down, and a single sample decides "no tool" often enough to be
  // useless. Two hits out of ten is the threshold the sequences were tuned on.
  return `${HEADER}
; Is a tool in the spindle? Result in global.atcToolHasBeenDetected.
; Reads gpIn[${config.toolSensorIn}], which is the M950 J${config.toolSensorIn} in atcConfig.g.

if !{exists(global.atcToolHasBeenDetected)}
\tglobal atcToolHasBeenDetected = true

set global.atcToolHasBeenDetected = true
var loopCounter = 0
var counter = 0

while var.loopCounter < 10
\tG4 P100
\tset var.loopCounter = iterations
\tset var.counter = {var.counter + sensors.gpIn[${config.toolSensorIn}].value}
\tset global.atcToolHasBeenDetected = var.counter < 2

if global.atcToolHasBeenDetected
\techo "Tool detected"
else
\techo "No tool detected"
`;
}
